server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        rewrite ^/api(.*)$ $1 break;
        proxy_pass http://gateway:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /uploads/ {
        proxy_pass http://gateway:8080;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    client_max_body_size 5m;
}
